export const styles = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(145deg, #f5f4f2 0%, #ece8e5 100%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    fontFamily: "'DM Sans', sans-serif",
  },
  card: {
    background: "white",
    borderRadius: 20,
    boxShadow: "0 12px 40px rgba(26,18,8,0.12), 0 4px 12px rgba(26,18,8,0.08)",
    padding: "20px 24px",
    width: "100%",
    maxWidth: 420,
    margin: "0 16px",
  },
  modeToggle: {
    display: "flex",
    background: "#e6e4e1",
    borderRadius: 99,
    padding: 4,
    marginBottom: 28,
    gap: 4,
  },
  modeBtn: {
    flex: 1,
    border: "none",
    borderRadius: 99,
    padding: "8px 0",
    fontSize: 13,
    cursor: "pointer",
    transition: "all 0.15s",
    fontFamily: "'DM Sans', sans-serif",
  },
  title: {
    fontFamily: "'DM Serif Display', serif",
    fontSize: 22,
    color: "#5a5555",
    letterSpacing: "-0.02em",
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 14,
    color: "#7a726f",
    fontWeight: 300,
  },
  label: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: "#4a4645",
    marginBottom: 4,
    letterSpacing: "0.02em",
    textTransform: "uppercase",
  },
  input: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px solid #d8d3d0",
    background: "white",
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    color: "#3f3a3a",
    outline: "none",
    transition: "border 0.15s, box-shadow 0.15s",
  },
  googleBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    width: "100%",
    padding: "9px 0",
    border: "1.5px solid #d8d3d0",
    borderRadius: 12,
    background: "white",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 500,
    fontFamily: "'DM Sans', sans-serif",
    color: "#3f3a3a",
    transition: "all 0.15s",
    boxShadow: "0 1px 3px rgba(26,18,8,0.06)",
  },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    margin: "12px 0",
    color: "#b8b2af",
    fontSize: 12,
  },
  primaryBtn: {
    display: "block",
    width: "100%",
    padding: "10px 0",
    borderRadius: 10,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    color: "white",
    textAlign: "center",
    transition: "all 0.15s",
    letterSpacing: "0.01em",
  },
};
